### PR TITLE
pop opcode modification

### PR DESCRIPTION
**Pull request by ashWhiteHat**
Part of https://github.com/privacy-scaling-explorations/zkevm-specs/issues/230

I introduced StepState and Instruction to `POP` opcode.
The circuit constraints and logics are aligned with zkevm-circuits.
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/pop.rs#L29

I found some not used functionalities, files and code duplication.
I also found functionalities only used for tests under the `src/zkevm_specs`.
These are bit confusing so I removed and refactored.

I would appreciate it if you could confirm.
Thank you!

### CODE REVIEW

**Review by han0110 — APPROVED** [review]
LGTM! Thanks for taking the time to remove duplicated codes.

**Comment by ashWhiteHat** [comment]
Hi @han0110 
I fixed the conflict.
The `POP` opcode is quite simple so I added its implementation.

I would appreciate it if you could confirm.
Thank you!

**Review by han0110 — APPROVED** [review]
The pop opcode refactor also LGTM!

**Review by ed255 — APPROVED** [review]
LGTM!  It's nice to see all that unused code removed :D

**Pull request merged**
