### PR TITLE
markdown spec for invalid_creation_code error

### PR DESCRIPTION
**Pull request by DreamWuGit**
circuit PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1292

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
pending on the circuit PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1292

**Comment by ChihChengLiang** [comment]
@silathdiir is this PR ready for review?

**Comment by silathdiir** [comment]
Yes, thanks. And also the related circuit PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1292.

Please help review when you have time. Thanks.

**Comment by ChihChengLiang** [comment]
Pending updates from @silathdiir as the circuit pr review suggests https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1292#pullrequestreview-1498577519

**Comment by ed255** [comment]
@silathdiir kindly ping to remind about updating this spec according to the merged circuit PR.  Let us know if you need help with anything!

**Comment by silathdiir** [comment]
> @silathdiir kindly ping to remind about updating this spec according to the merged circuit PR. Let us know if you need help with anything!

Sorry for delay. Will try to continue on this PR in this month (add `invalid_creation_code` spec code and update `return_revert` spec).

**Comment by KimiWu123** [comment]
moved to #478

**Pull request closed without merging**
