### PR TITLE
Update state circuit spec from impl

### LINKED ISSUE #199: Update state circuit specs based on circuit impl
Based on these notes (Annotated with FIXME are the differences between spec and implementation):
https://github.com/appliedzkp/zkevm-circuits/commit/adcab5ce9d026dbef81c1af3bbd71a3d0a20fb51

### PR DESCRIPTION
**Pull request by ed255**
The main change is that the lexicographic ordering now includes the RWC
as well (so we don't need to check the RWC is monotonically increasing
individually); and that the lexicographic ordering uses a LowerThan
comparison collecting all keys into 16 bit limbs.

Update the spec notes to use two numbers to be more clear.

Use column key names instead of key indexes to make the constraints more
clear (like in the implementation)

Resolve https://github.com/appliedzkp/zkevm-specs/issues/199

### CODE REVIEW

**Comment by ed255** [comment]
@lispc could you help review this PR?

**Comment by lispc** [comment]
only one thing to discuss:  in the spec "little endian" is used in limbs sorting. while in the circuit, i am not sure whether it is also "little endian"? from the imple codes, it seems big endian.

**Comment by lispc** [comment]
only one thing to discuss:  in the spec "little endian" is used in limbs sorting. while in the circuit, i am not sure whether it is also "little endian"? from the imple codes, it seems big endian.

**Review by lispc — APPROVED** [review]

**Comment by ed255** [comment]
> only one thing to discuss: in the spec "little endian" is used in limbs sorting. while in the circuit, i am not sure whether it is also "little endian"? from the imple codes, it seems big endian.

You're right, the limbs array is implemented in big endian in the circuit and in little endian in this spec; but as Miha says, both are equivalent because it's a matter of how the `lower than` gadget works.  I've added a comment with the list of tags in order used in the lexicographic ordering to make it more explicit which is the order defined in this spec.

**Review by miha-stopar — APPROVED** [review]

**Pull request merged**
