### PR TITLE
[WIP] Add non-existing check for SLOAD/SSTORE

### PR DESCRIPTION
**Pull request by CPerezz**
In order to make account_storage reads/writes we need first to assert
that the storage for a particular account exists. Not only the account
but also the storage associated to it.

This adds into the table specs and implementation a new tag for
`AccountStorage` called `AccountStorageTag`. This allows to lookup the
existance of an account storage.

It also ports `SLOAD` and `SSTORE` to make usage of the lookups of existance.

Finally, updates the tests of these opcodes adding any required methods for them.

### CODE REVIEW

**Comment by CPerezz** [comment]
While discussing with @han0110 about the PR, he mentioned that why we weren't treating the Storage on the same way as we do with memory. 
Basically this PR tries to avoid the chance of making lookups to non-existing account storages (which will fail and collapse the entire proof). Instead, they check the non-existance of an account and simply continue with the proof.

Han suggested that this could also have been done assuming that if you read and there's a non-existing data set, you simply read 0's as in mem copies.
Same goes for storage.

This is subject to some MPT considerations:
>  but we can implement that in the State circuit just like how we handle the memory out of range read, but I had the impression that this will make the MPT check difficult
> Perhaps need to check with @miha-stopar  and tell him that we no matter what need to perform the operation “write to empty storage”, and see how MPT needs to adjust, then finally dicide how to implement that in State/EVM circuit.

Same would happen with read from non-existing storage which would read zeros.

cc: @miha-stopar @ed255 @ChihChengLiang

**Comment by miha-stopar** [comment]
> While discussing with @han0110 about the PR, he mentioned that why we weren't treating the Storage on the same way as we do with memory. Basically this PR tries to avoid the chance of making lookups to non-existing account storages (which will fail and collapse the entire proof). Instead, they check the non-existance of an account and simply continue with the proof.
> 
> Han suggested that this could also have been done assuming that if you read and there's a non-existing data set, you simply read 0's as in mem copies. Same goes for storage.
> 
> This is subject to some MPT considerations:
> 
> > but we can implement that in the State circuit just like how we handle the memory out of range read, but I had the impression that this will make the MPT check difficult
> > Perhaps need to check with @miha-stopar  and tell him that we no matter what need to perform the operation “write to empty storage”, and see how MPT needs to adjust, then finally dicide how to implement that in State/EVM circuit.
> 
> Same would happen with read from non-existing storage which would read zeros.
> 
> cc: @miha-stopar @ed255 @ChihChengLiang

When the child in branch where the key should be inserted is empty, this is already working (in this case a placeholder leaf is added and checked to have 0 value). Differently, when `getProof` returns an existing leaf (where the new leaf would land too and thus a branch needs to be created), some additional things would need to be implemented in the MPT circuit. But shouldn't take a lot of time as some functionality from the non-existing checks could be reused.

**Comment by CPerezz** [comment]
I think it's fair to add slighly more complexity to the State circuit and avoid increasing it in the MPT circuit.
@han0110 WDYT?  That means IIUC that we don't need to support the SSTORE write to nothing case, but we still need to support the SLOAD read from nothing case with the non-existance lookup.

**Comment by CPerezz** [comment]
Closing this. See https://hackmd.io/5FHDL-6RSRCOd5l_GMndZA and expect a new PR with a different approach than addressing this in the EVMCircuit

**Pull request closed without merging**
