### PR TITLE
doc/reformat state-proof.md

### PR DESCRIPTION
**Pull request by KimiWu123**
Adding bullet points to break lines in description. 

There is no line breaks in the current doc as below.

截圖 2023-03-21 下午3 05 06

### CODE REVIEW

**Comment by ashWhiteHat** [comment]
Hi @KimiWu123 
Is ready for review?

**Comment by KimiWu123** [comment]
> Hi @KimiWu123 Is ready for review?

Yes! it's ready for review.

**Comment by ashWhiteHat** [comment]
Hi @KimiWu123 
I changed the serial numbers because of markdown perspective.
https://github.com/privacy-scaling-explorations/zkevm-specs/pull/391/files#diff-383bd0a8138e9b40964a4046a8b879413643629705529274f64ba6270fb350eaR44
Could you reflect this change to this PR accordingly?

**Comment by KimiWu123** [comment]
Make sure after apply your format, it would look like this. Does it fit your expectation?
截圖 2023-03-22 下午3 15 03


If it's what you expected, I prefer the format of my PR like below. Bcs it looks more consistent with code comment. How do you think?
截圖 2023-03-22 下午3 18 18

**Review by ashWhiteHat — APPROVED** [review]
LGTM!

**Pull request merged**
